Update menu

diff --git a/menu/menu b/menu/menu
--- a/menu/menu
+++ b/menu/menu
@@ -1,257 +1,300 @@
 #!/bin/bash
-# COLOR VALIDATION
-clear
-y='\033[1;33m' #yellow
-BGX="\033[42m"
-CYAN="\033[96m"
-z="\033[96m"
-f="\033[1;97;41m"
-RED='\033[0;31m'
-NC='\033[0m'
-gray="\e[1;30m"
-Blue="\033[0;34m"
-green='\033[0;32m'
-grenbo="\e[92;1m"
-purple="\033[1;95m"
-YELL='\033[0;33m'
-#INTALLER-UDP
-UDPX="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
-ISP=$(cat /root/.info/.isp)
-CITY=$(cat /root/.info/.city)
-IPVPS=$(curl -s ipv4.icanhazip.com)
-NS=$(cat /etc/xray/dns)
-domain=$(cat /etc/xray/domain)
-RAM=$(free -m | awk 'NR==2 {print $2}')
-USAGERAM=$(free -m | awk 'NR==2 {print $3}')
-MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
-LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
-MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
-CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
-DATEVPS=$(date +'%d-%m-%Y')
-TIMEZONE=$(printf '%(%H-%M-%S)T')
-SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
-clear
+REDBLD="\033[0m\033[91;1m"
+Green="\e[92;1m"
+RED="\033[1;31m"
+YELLOW="\033[33m"
+BLUE="\033[36m"
+FONT="\033[0m"
+GREENBG="\033[42;37m"
+REDBG="\033[41;37m"
+NC='\e[0m'
 MYIP=$(curl -sS ipv4.icanhazip.com)
+######################################
+#IPVPS=$(curl -s ipv4.icanhazip.com)
+#ISP=$(cat /etc/xray/isp)
+#CITY=$(cat /etc/xray/city)
+#domain=$(cat /etc/xray/domain)
+#RAM=$(free -m | awk 'NR==2 {print $2}')
+#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')
+
+#uptime="$(uptime -p | cut -d " " -f 2-10)"
+#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
+#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
+#cpu_usage+=" %"
+# // Gettings Info
+function print_install() {
+echo -e "${BLUE} =============================== ${FONT}"
+echo -e "${YELLOW} # $1 ${FONT}"
+echo -e "${BLUE} =============================== ${FONT}"
+sleep 1
+}
+function print_success() {
+if [[ 0 -eq $? ]]; then
+echo -e "${BLUE} =============================== ${FONT}"
+echo -e "${Green} # $1 berhasil dipasang"
+echo -e "${BLUE} =============================== ${FONT}"
+sleep 2
+fi
+}
+function Rename() {
+clear
+echo -e "${YELLOW}----------------------------------------------------------${NC}"
+echo -e "\033[96;1m                      Welcome To Script AMGANTENG              \033[0m"
+echo -e "${YELLOW}----------------------------------------------------------${NC}"
 echo ""
-izinsc="https://raw.githubusercontent.com/Ilham24022001/ijin/refs/heads/main/ijin"
-# USERNAME
+sleep 3s
+echo -e "    ----------------------------------"
+echo -e "   |\e[1;32mPlease Select a Options \e[0m|"
+echo -e "    ----------------------------------"
+echo -e "     \e[1;32m1)\e[0m Rename Script"
+echo -e "     \e[1;32m2)\e[0m Default "
+echo -e "   ------------------------------------"
+read -p "   Please select numbers 1-2 or Any Button(Default) : " host
+echo ""
+if [[ $host == "1" ]]; then
+clear
+echo ""
+echo ""
+echo -e "   \e[1;36m_______________________________$NC"
+echo -e "   \e[1;32m      CHANGES NAME SCRIPT $NC"
+echo -e "   \e[1;36m_______________________________$NC"
+echo -e ""
+read -p "   INPUT YOUR NAME :   " host1
+read -p "   INPUT PAS ADMIN :   " host11
+rm /etc/xray/username
+if [[ $host11 == 123@Am ]]; then
+echo $host1 >> /etc/xray/username
+echo ""
+clear
+print_success "Rename Script"
+sleep 3
+menu
+else
+echo "AM GANTENG VPS" > /etc/xray/username
+clear
+echo -e "${RED} Mohon Maaf Sepertinya Anda Bukan Owner ${NC}"
+sleep 3
+clear
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    echo -e ""
+    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
+    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
+    echo -e "             \033[0;33mContact Admin :\033[0m"
+    echo -e "      \033[2;32mWhatsApp\033[0m wa.me/6287758825817"
+	echo -e "      \033[2;32mTelegram\033[0m t.me/@Amstore_vpn"
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    sleep 3
+    print_success "Script Name Default"
+    sleep 2
+    menu
+fi
+elif [[ $host == "2" ]]; then
+rm /etc/xray/username
+echo "GESEL" > /etc/xray/username
+clear
+print_success "Script Name Default"
+sleep 3
+menu
+fi
+}
+######################################
+# // USERNAME IZIN IPP
 rm -f /usr/bin/user
-username=$(curl ${izinsc} | grep $MYIP | awk '{print $2}')
+username=$(curl -sS https://raw.githubusercontent.com/Ilham24022001/permisi/main/ip | grep $MYIP | awk '{print $2}')
 echo "$username" >/usr/bin/user
-# validity
 rm -f /usr/bin/e
-valid=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
-echo "$valid" >/usr/bin/e
-# DETAIL ORDER
+valid=$(curl -sS https://raw.githubusercontent.com/Ilham24022001/permisi/main/ip | grep $MYIP | awk '{print $3}')
+echo "$valid" > /usr/bin/e
+
+clear
+######################################
+# // DETAIL ORDER IZIN IP
 username=$(cat /usr/bin/user)
 oid=$(cat /usr/bin/ver)
 exp=$(cat /usr/bin/e)
+######################################
 clear
-# CERTIFICATE STATUS
+# // DAYS LEFT
 d1=$(date -d "$valid" +%s)
 d2=$(date -d "$today" +%s)
 certifacate=$(((d1 - d2) / 86400))
-# VPS Information
-DATE=$(date +'%Y-%m-%d')
-datediff() {
-    d1=$(date -d "$1" +%s)
-    d2=$(date -d "$2" +%s)
-    echo -e "$COLOR1 $NC Expiry In   : $(( (d1 - d2) / 86400 )) Days"
-}
-mai="datediff "$Exp" "$DATE""
-
-# Status Expired Or Active
-Info="(${green}Active${NC})"
-Error="(${RED}Expired${NC})"
-today=`date -d "0 days" +"%Y-%m-%d"`
-Exp1=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
-if [[ $today < $Exp1 ]]; then
-sts="${Info}"
+if [[ $certifacate -le 0 ]]; then
+masaaktif="EXPAIRED"
 else
-sts="${Error}"
+masaaktif="${certifacate} Day"
 fi
 clear
-
-# OS Uptime
-uptime="$(uptime -p | cut -d " " -f 2-10)"
-
-# Getting CPU Information
-cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
-cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
-cpu_usage+=" %"
-
-WKT=$(curl -s ipinfo.io/timezone )
-DAY=$(date +%A)
-DATE=$(date +%m/%d/%Y)
-DATE2=$(date -R | cut -d " " -f -5)
-IPVPS=$(curl -s ipv4.icanhazip.com)
-cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
-cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
-freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
-tram=$( free -m | awk 'NR==2 {print $2}' )
-uram=$( free -m | awk 'NR==2 {print $3}' )
-fram=$( free -m | awk 'NR==2 {print $4}' )
-clear
+######################################
+# // GETTINGS SYSTEM
 ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
-dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
-haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
-xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
-nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
-#Status | Geo Project
-clear
-# STATUS SERVICE  SSH 
-if [[ $ssh_service == "running" ]]; then 
-   status_ssh="${green}ON🟢${NC}"
-else
-   status_ssh="${RED}🔴${NC} "
-fi
 
-# // SSH Websocket Proxy
+dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
+
+haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
+
+xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
+
+nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
+
+clear
+######################################
+# // RUNNING SSH
+######################################
+if [[ $ssh_service == "running" ]]; then 
+   status_ssh="\033[92;1mON${NC}"
+else
+   status_ssh="\033[91;1mOFF${NC} "
+fi
+######################################
+# // RUNNING WEBSOCKET
+######################################
 ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
 if [[ $ssh_ws == "running" ]]; then
-    status_ws_epro="${green}ON🟢${NC}"
+    status_ws_epro="\033[92;1mON${NC}"
 else
-    status_ws_epro="${RED}🔴${NC} "
+    status_ws_epro="\033[91;1mOFF${NC} "
 fi
-
-# STATUS SERVICE HAPROXY
+######################################
+# RUNNING HAPROXY
+######################################
 if [[ $haproxy_service == "running" ]]; then 
-   status_haproxy="${green}ON🟢${NC}"
+   status_haproxy="\033[92;1mON${NC}"
 else
-   status_haproxy="${RED}🔴${NC} "
+   status_haproxy="\033[91;1mOFF${NC} "
 fi
-
-# STATUS SERVICE XRAY
+######################################
+# RUNNING XRAY
+######################################
 if [[ $xray_service == "running" ]]; then 
-   status_xray="${green}ON🟢${NC}"
+   status_xray="\033[92;1mON${NC}"
 else
-   status_xray="${RED}🔴${NC} "
+   status_xray="\033[91;1mOFF${NC} "
 fi
-
-# STATUS SERVICE NGINX
+######################################
+# RUNNING NGINX
+######################################
 if [[ $nginx_service == "running" ]]; then 
-   status_nginx="${green}ON🟢${NC}"
+   status_nginx="\033[92;1mON${NC}"
 else
-   status_nginx="${RED}🔴${NC} "
+   status_nginx="\033[91;1mOFF${NC} "
+fi
+######################################
+# RUNNING DROPBEAR
+######################################
+if [[ $dropbear_service == "running" ]]; then 
+   status_dropbear="\033[92;1mGOOD${NC}"
+else
+   status_dropbear="\033[91;1mCRAZY${NC} "
 fi
 
-# STATUS SERVICE Dropbear
-if [[ $dropbear_service == "running" ]]; then 
-   status_dropbear="${green}ON🟢${NC}"
-else
-   status_dropbear="${RED}🔴${NC} "
-fi
-#####INFOAKUN
+# \\ Vless account //
 vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
 let vla=$vlx/2
+# \\ Vmess account //
 vmc=$(grep -c -E "^### " "/etc/xray/config.json")
 let vma=$vmc/2
+# \\ Trojan account //
 ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
 trx=$(grep -c -E "^#! " "/etc/xray/config.json")
 let trb=$trx/2
-ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
+# \\ shadowsocks account //
+ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
 let ssa=$ssx/2
 
-###########
-KANAN="\033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC"
-KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
-########
-r="\033[1;31m"  #REDTERANG
-a=" ${CYAN}ACCOUNT PREMIUM" 
-#clear
-echo -e " "
-echo -e " ${z}╭═════════════════════════════════════════════════════════╮${NC}"
-echo -e " ${z}│$NC${f}    WELCOME TO  AM GANTENG STORE AUTOSCRIPT PREMIUM      $NC${z}│$NC"
-echo -e " ${z}╰═════════════════════════════════════════════════════════╯${NC}"
-echo -e " ${z}══════════════════════════════════════════════════════════${NC}"
-echo -e " ${GREEN}● ${LIGHTGREEN}● ${CYAN}● ${LIGHTBLUE}● ${BLUE}● ${PURPLE}● ALL OS SUPPORT UBUNTU ${PINK}● ${WHITE}● ${NC}${RED}● ${ORANGE}●"
-echo -e " ${z}$NC$r ⇲ $NC$y ISP ${NC}           $Blue=$NC $ISP${NC}"
-echo -e " ${z}$NC$r ⇲ $NC$y CITY ${NC}          $Blue=$NC $CITY${NC}"
-echo -e " ${z}$NC$r ⇲ $NC$y Server RAM ${NC}    $Blue=$NC $tram MB $NC"
-echo -e " ${z}$NC$r ⇲ $NC$y Core Cpu ${NC}      $Blue=$NC $CORE${NC}" CPU
-echo -e " ${z}$NC$r ⇲ $NC$y Uptime Server ${NC} $Blue=$NC $SERONLINE${NC}"
-echo -e " ${z}$NC$r ⇲ $NC$y Date ${NC}          $Blue=$NC $DATEVPS${NC}"
-echo -e " ${z}$NC$r ⇲ $NC$y Time ${NC}          $Blue=$NC $TIMEZONE${NC}"
-echo -e " ${z}$NC$r ⇲ $NC$y Domain ${NC}        $Blue=$NC $domain${NC}"
-echo -e " ${z}══════════════════════════════════════════════════════════${NC}"
-echo -e "            ${KIRI} ${Green}INFORMATION ACCOUNT ON VPS${NC} ${KANAN}"
-echo -e "          ${NC}┌─────────────────────────────────────┐${NC}"
-echo -e "                 ${CYAN}ACCOUNT SSH/OVPN/UDP${NC}   $y=$NC $ssh1${NC}"
-echo -e "                 ${CYAN}ACCOUNT VMESS/WS/GRPC${NC}  $y=$NC $vma$NC"
-echo -e "                 ${CYAN}ACCOUNT VLESS/WS/GRPC${NC}  $y=$NC $vla$NC" 
-echo -e "                 ${CYAN}ACCOUNT TROJAN/WS/GRPC${NC} $y=$NC $trb${NC}"
-echo -e "                 ${CYAN}ACCOUNT SHADOW/WS/GRPC${NC} $y=$NC $ssa${NC}"
-echo -e "          ${NC}└─────────────────────────────────────┘${NC}"
-echo -e "               ${KIRI} ${RED} AM GANTENG STORE TUNNELING  ${NC} ${KANAN}"
-echo -e " ${z}╭════════════════╮╭══════════════════╮╭════════════════════╮${NC}"
-echo -e " ${z}│ ${NC}$y SSH$NC : $status_ssh" "       $y NGINX$NC : $status_nginx" "       $y XRAY$NC : $status_xray     $NC${z}│$NC" 
-echo -e " ${z}│ ${NC}$y WS-ePRO$NC : $status_ws_epro" "   $y DROPBEAR$NC : $status_dropbear" "    $y HAPROXY$NC : $status_haproxy  $NC${z}│$NC" 
-echo -e " ${z}╰════════════════╯╰══════════════════╯╰════════════════════╯${NC}"
-echo -e "            ${KIRI} ${Green}⇱ SELMA MULIATI VPN ⇲${NC} ${KANAN}"
-echo -e "    ${z}══════════════════════════════════════════════════════${NC}"
-echo -e "           ${z}$NC [${w}01${NC}]$white MENU SSH$NC      ${z}│$NC [${w}05${NC}]$white MENU SSWS$NC  ${z}$NC"
-echo -e "           ${z}$NC [${wh}02${NC}]$white MENU VMESS$NC   ${z}│$NC [${w}06${NC}]$white MENU NOOBZVPN$NC ${z}$NC"
-echo -e "           ${z}$NC [${wh}03${NC}]$white MENU VLESS$NC   ${z}│$NC [${w}07${NC}]$white SPEEDTEST$NC ${z} $NC"
-echo -e "           ${z}$NC [${wh}04${NC}]$white MENU TROJAN$NC  ${z}│$NC [${w}08${NC}]$white MENU UTILITY$NC ${z} $NC"
-echo -e "    ${z}══════════════════════════════════════════════════════${NC}"
-echo -e "            ${KIRI}${z} INFORMATION YOUR ACTIVE PERIOD ${z}${KANAN}"
-echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
-echo -e " ${z}│$NC${z} Developer$NC  ${z}=$NC AM GANTENG"
-echo -e " ${z}│$NC${z} My Love$NC    ${z}=$NC SELMA MULIATI"
-echo -e " ${z}│$NC${z} IP ADDRESS ${z}=$NC $IPVPS${NC}"
-echo -e " ${z}│$NC${z} User$NC       ${z}=$NC $username"
-echo -e " ${z}│$NC${z} Exp Script$NC ${z}=$NC $exp $certifacate Days$NC $sts"
-echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
-echo -e "     ${KIRI}${z}THANKS YOU FOR USING SCRIPT AM GANTENG${z}${KANAN}"
-echo -e ""
-read -p " PILIH MENU DENGAN CARA KETIK 1/8 : " opt
-echo -e ""
-case $opt in
-1 | 01)
+# // NEWBIE TUNNELING | NB PROJECT
+# // WHATSAPP : 087758825817
+# // TELEGRAM : AMGANTENG
+
+
+function Newbie_Banner() {
 clear
-m-sshws
-;;
-2 | 02)
-clear
-m-vmess
-;;
-3 | 03)
-clear
-m-vless
-;;
-4 | 04)
-clear
-m-trojan
-;;
-5 | 05)
-clear
-m-ssws
-;;
-6 | 06)
-clear
-m-noob
-;;
-7 | 07)
-clear
-speedtest
-;;
-7 | 07)
-clear
-speedtest
-menu
-;;
-8 | 08)
-clear
-menu-x
-;;
-0 | 00)
-exit
-;;
-x)
-menu
-;;
-*) clear ;
-echo -e 
-menu
-;;
+BOX_WIDTH=47
+TEXT="$(cat /etc/xray/username)"
+TEXT_LENGTH=${#TEXT}
+TEXT_COLOR="\033[97;1m\033[41m"
+RESET_COLOR="\033[0m"
+LEFT_PADDING=$(( (BOX_WIDTH - TEXT_LENGTH) / 2 ))
+RIGHT_PADDING=$(( BOX_WIDTH - TEXT_LENGTH - LEFT_PADDING ))
+LEFT_SPACE=$(printf '\033[41m%*s\033[0m' $LEFT_PADDING '')
+RIGHT_SPACE=$(printf '\033[41m%*s\033[0m' $RIGHT_PADDING '')
+echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
+echo -e "\033[97;1m  \033[0m${LEFT_SPACE}${TEXT_COLOR}${TEXT}${RESET_COLOR}${RIGHT_SPACE} \033[97;1m \033[0m"
+echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
+}
+
+
+
+function Service_System_Operating() {
+echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
+echo -e "\033[96;1m \e[97m SYSTEM          : $(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
+echo -e "\033[96;1m \e[97m RAM             : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
+echo -e "\033[96;1m \e[97m UPTIME          : $(uptime -p | cut -d " " -f 2-10)\033[0m "
+echo -e "\033[96;1m \e[97m IP VPS          : $(curl -s ipv4.icanhazip.com)     \033[0m "
+echo -e "\033[96;1m \e[97m CITY            : $(cat /etc/xray/city)    \033[0m "
+echo -e "\033[96;1m \e[97m ISP             : $(cat /etc/xray/isp)    \033[0m "
+echo -e "\033[96;1m \e[97m DOMAIN          : $(cat /etc/xray/domain)    \033[0m "
+echo -e "\033[96;1m───────────────────────────────────────────────────\033[0m"
+echo -e "\033[97;1m             \033[0m \033[93;1m\033[0m \033[92;1m[ SERVICE STATUS ]\033[0m \033[97;1m \033[0m " 
+}
+
+
+
+function Service_Status() {
+echo -e "\033[96;1m───────────────────────────────────────────────────\033[0m "
+echo -e "\033[96;1m \e[0m\e[33m PROXY :\e[0m $status_haproxy  \e[0m|\e[33m NGINX :\e[0m $status_nginx  \e[0m|\e[33m XRAY :\e[0m $status_xray \e[0m| $status_dropbear  \e[96;1m   \e[0m "
+}
+
+
+
+function Acces_Use_Command() {
+echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
+echo -e "\033[96;1m  \e[34m1.)\e[93m \e[97m SSH/OPENVPN         \e[34m7.)\e[93m \e[97m BOT TELEGRAM   \e[96;1m\e[0m"   
+echo -e "\033[96;1m  \e[34m2.)\e[93m \e[97m XRAY MANAGER        \e[34m8.)\e[93m \e[97m UPDATE SCRIPT  \e[96;1m\e[0m"
+echo -e "\033[96;1m  \e[34m3.)\e[93m \e[97m XRAY TROJAN         \e[34m9.)\e[93m \e[97m BACKUP RESTOR  \e[96;1m\e[0m"
+echo -e "\033[96;1m  \e[34m4.)\e[93m \e[97m SLOWDNS            \e[34m10.)\e[93m \e[97m FEATURES       \e[96;1m\e[0m"
+echo -e "\033[96;1m  \e[34m5.)\e[93m \e[97m NOOBZVPNS          \e[34m11.)\e[93m \e[97m REBOOT         \e[96;1m\e[0m"
+echo -e "\033[96;1m  \e[34m6.)\e[93m \e[97m RENAME SC          \e[34m12.)\e[93m \e[97m MENU        \e[96;1m\e[0m"
+echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
+echo -e "\033[96;1m                \e[31m\e[93m  \e[91m   [ EXIT ]          \e[96;1m\e[0m"
+echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
+echo -e "\033[96;1m┌──────────────────────────────────────────────────┐\033[0m"
+echo -e "\033[96;1m   \e[0m\e[33m      kesuksesan itu dari diri sendiri \033[0m"
+echo -e "\033[96;1m└──────────────────────────────────────────────────┘\033[0m"
+}
+
+
+
+function Select_Display() {
+echo
+read -p "Select From option [1/11 or x] :  " hallo
+case $hallo in
+1) clear ; m-ssh ;; # menu ssh
+2) clear ; m-xray ;; # menu vmess
+3) clear ; m-tro ;; # menu vles
+4) clear ; sd ;; # menu trojan
+5) clear ; m-noobz ;; # menu sadowsocks
+6) clear ; Rename ;; # menu noobzvps
+7) clear ; m-bot ;; # menu bot telegram
+8) clear ; wget -q https://raw.githubusercontent.com/Ilham24022001/Gantengzz/main/update.sh && bash update.sh ;; #Update script
+9) clear ; m-bkp ;; # menu backup
+10) clear ; m-ftr ;; # menu managers
+11)clear ; reboot ;; # menu managers
+*) welcome ;; # Back To Home Welcome
 esac
+}
+
+
+Newbie_Banner
+Service_System_Operating
+Service_Status
+Acces_Use_Command
+Select_Display
+
+
+
+
+
+
+
